### ISSUE TITLE
Error when devDependencies are missing

### ISSUE THREAD

**Issue by kumavis** [dominykas/allow-scripts#44]
when run after `yarn install --production`, you encounter the following error
```
npm notice created a lockfile as npm-shrinkwrap.json. You should commit this file.


Error: Failed to read the installed tree - you might want to `rm -rf node_modules && npm i --ignore-scripts`.
    at Object.exports.run (/www/node_modules/allow-scripts/lib/index.js:93:15)
    at Object.<anonymous> (/www/node_modules/allow-scripts/bin/allow-scripts.js:13:7)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
error Command failed with exit code 1.
```

**Comment by dominykas** [comment]
Can you provide a `package.json`?

I'm not a yarn user.

**Comment by dominykas** [comment]
Closing, as no response. Feel free to reopen with relevant information.
